#!/usr/bin/env bash

TEMPORARY_FILE_PATH=$1

COMMIT_MSG=`head -n1 $TEMPORARY_FILE_PATH`

if [[ $COMMIT_MSG =~ "SKIP VERSION" ]]; then 
    echo "SKIPPING VERSION UPDATE"
    exit 0
fi

echo "Updating Version"

./scripts/update-version.sh

git add common/version.go

echo "Commit again with the words SKIP VERSION in the commit message"

exit 1