ARG CADENCE_IMAGE=ubercadence/server:latest

FROM ${CADENCE_IMAGE}

RUN apk add --update --no-cache ca-certificates py-pip mysql-client
RUN pip install cqlsh

COPY docker/start.sh /start.sh

CMD /start.sh
