ALTER TABLE executions ADD created_time timestamp;
ALTER TABLE history_node ADD created_time timestamp;
ALTER TABLE history_tree ADD created_time timestamp;
ALTER TABLE domains ADD created_time timestamp;
ALTER TABLE domains_by_name_v2 ADD created_time timestamp;
ALTER TABLE queue ADD created_time timestamp;
ALTER TABLE queue_metadata ADD created_time timestamp;
ALTER TABLE queue_metadata ADD last_updated_time timestamp;