{
 "title": "Cadence Matching",
 "time": { "from": "2024-12-10T17:20:49.632Z", "to": "2024-12-10T17:26:01.274Z" },
 "panels": [
  { "title": "Add & Poll QPS and Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AddDecisionTask QPS per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tasklist) (\n  rate(cadence_requests_per_tl{\n    operation=\"AddDecisionTask\"\n  }[10s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PollForDecisionTask QPS per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tasklist) (\n  rate(cadence_requests_per_tl{\n    operation=\"PollForDecisionTask\"\n  }[10s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AddDecisionTask p99 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(cadence_latency_per_tl_bucket{operation=\"AddDecisionTask\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PollForDecisionTask p99 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(cadence_latency_per_tl_bucket{operation=\"PollForDecisionTask\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AddDecisionTask p50 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cadence_latency_per_tl_bucket{operation=\"AddDecisionTask\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PollForDecisionTask p50 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(cadence_latency_per_tl_bucket{operation=\"PollForDecisionTask\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sync vs Async Matches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Sync Match Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(tasklist)(rate(syncmatch_latency_per_tl_count{operation=\"AddDecisionTask\"}[10s])) / sum by (tasklist) (rate(cadence_requests_per_tl{operation=\"AddDecisionTask\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Sync Matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(tasklist) (\n  rate(syncmatch_latency_per_tl_sum{operation=\"AddDecisionTask\"}[10s])\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Async Matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(tasklist) (\n  rate(asyncmatch_latency_per_tl_sum{tasklistType=\"decision\"}[10s])\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Sync Match p99 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(syncmatch_latency_per_tl_bucket{operation=\"AddDecisionTask\"}[10s]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Async Match p99 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(asyncmatch_latency_per_tl_bucket{tasklistType=\"decision\"}[10s]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Sync Match p50 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(syncmatch_latency_per_tl_bucket{operation=\"AddDecisionTask\"}[10s]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DecisionTask Async Match p50 latency per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(asyncmatch_latency_per_tl_bucket{tasklistType=\"decision\"}[10s]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "DecisionTask Backlog per tasklist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(tasklist) (rate(task_backlog_per_tl{tasklistType=\"decision\"}[10s]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Adaptive Partition Scaler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Partition Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "max(task_list_partition_config_num_read{tasklist=\"my_tasklist\"})",
     "legendFormat": "read_partitions"
    },
    {
     "expr": "max(task_list_partition_config_num_write{tasklist=\"my_tasklist\"})",
     "legendFormat": "write_partitions"
    }
   ]
  }
 ]
}